on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: Notepad pipeline
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate notepad
        timeout-minutes: 5
        run: ./run
      - name: Debug
        run: for FILE in ./target/*; do echo "$FILE"; cat "$FILE"; done
        if: always()
      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          path: 'target'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: always()


